// src/vue/Ticker.vue
<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, computed } from 'vue';
import type { TickerOptions } from '../core/types';
import { createTicker, mount, unmount } from '../vanilla/render';
import '../style.css';

interface Props extends TickerOptions {
  as?: 'div' | 'section' | 'article' | 'nav' | 'footer' | 'header';
}

const props = withDefaults(defineProps<Props>(), {
  duration: 20,
  direction: 'left',
  pauseOnHover: false,
  interactiveClones: false,
  class: '',
  as: 'div',
});

const emit = defineEmits<{
  ready: [];
}>();

const containerRef = ref<HTMLElement | null>(null);
const isReady = ref(false);
let tickerInstance: ReturnType<typeof createTicker> | null = null;

const combinedClass = computed(() => {
  return `ticker-wrapper ${props.class}`.trim();
});

onMounted(() => {
  mount();

  const container = containerRef.value;
  if (!container) return;

  setTimeout(() => {
    isReady.value = true;
    emit('ready');
  }, 0);

  tickerInstance = createTicker({
    duration: props.duration,
    direction: props.direction,
    pauseOnHover: props.pauseOnHover,
    interactiveClones: props.interactiveClones,
    class: props.class,
  });
  tickerInstance.mount();
});

onBeforeUnmount(() => {
  if (tickerInstance) {
    tickerInstance.unmount();
  }
});
</script>

<template>
  <component
    :is="props.as"
    ref="containerRef"
    :class="combinedClass"
    data-ticker=""
    :data-duration="props.duration"
    :data-direction="props.direction"
    :data-pause-on-hover="props.pauseOnHover ? 'true' : 'false'"
    :data-interactive-clones="props.interactiveClones ? 'true' : 'false'"
    :data-ready="isReady ? 'true' : 'false'"
    data-active="true"
    :style="{ '--ticker-duration': `${props.duration}s` }"
  >
    <div
      :class="['ticker-track', props.pauseOnHover ? 'ticker-pause-on-hover' : '']"
      data-ticker-track=""
    >
      <div class="ticker-content" data-ticker-content="">
        <slot />
      </div>
    </div>
  </component>
</template>

// src/svelte/Ticker.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import type { TickerOptions } from '../core/types';
  import { createTicker, mount, unmount } from '../vanilla/render';
  import '../style.css';

  export let duration: TickerOptions['duration'] = 20;
  export let direction: TickerOptions['direction'] = 'left';
  export let pauseOnHover: TickerOptions['pauseOnHover'] = false;
  export let interactiveClones: TickerOptions['interactiveClones'] = false;
  export let className: string = '';

  let container: HTMLElement;
  let isReady = false;
  let tickerInstance: ReturnType<typeof createTicker> | null = null;

  const combinedClass = `ticker-wrapper ${className}`.trim();

  onMount(() => {
    mount();

    setTimeout(() => {
      isReady = true;
    }, 0);

    tickerInstance = createTicker({
      duration,
      direction,
      pauseOnHover,
      interactiveClones,
      class: className,
    });
    tickerInstance.mount();
  });

  onDestroy(() => {
    if (tickerInstance) {
      tickerInstance.unmount();
    }
  });
</script>

<div
  bind:this={container}
  class={combinedClass}
  data-ticker=""
  data-duration={String(duration)}
  data-direction={direction}
  data-pause-on-hover={pauseOnHover ? 'true' : 'false'}
  data-interactive-clones={interactiveClones ? 'true' : 'false'}
  data-ready={isReady ? 'true' : 'false'}
  data-active="true"
  style="--ticker-duration: {duration}s"
>
  <div
    class="ticker-track"
    class:ticker-pause-on-hover={pauseOnHover}
    data-ticker-track=""
  >
    <div class="ticker-content" data-ticker-content="">
      <slot />
    </div>
  </div>
</div>
