// src/react/Ticker.tsx
import React, { useEffect, useRef, useState } from 'react';
import type { TickerOptions } from '../core/types';
import { createTicker, mount, unmount } from '../vanilla/render';
import '../style.css';

export interface TickerProps extends TickerOptions {
  children: React.ReactNode;
  className?: string;
}

export interface TickerRootProps extends TickerProps {
  as?: 'div' | 'section' | 'article' | 'nav' | 'footer' | 'header';
}

export function Root({
  children,
  className = '',
  duration = 20,
  direction = 'left',
  pauseOnHover = false,
  as: Component = 'div',
  ...props
}: TickerRootProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [isReady, setIsReady] = useState(false);

  useEffect(() => {
    mount();

    const container = containerRef.current;
    if (!container) return;

    const content = container.querySelector<HTMLElement>('.ticker-content');
    if (!content) return;

    const wrapper = document.createElement('div');
    wrapper.classList.add('ticker-wrapper', className);
    wrapper.setAttribute('data-ticker', '');
    wrapper.setAttribute('data-duration', String(duration));
    wrapper.setAttribute('data-direction', direction);
    wrapper.setAttribute('data-pause-on-hover', pauseOnHover ? 'true' : 'false');
    wrapper.setAttribute('data-ready', 'false');
    wrapper.setAttribute('data-active', 'true');
    wrapper.style.setProperty('--ticker-duration', `${duration}s`);

    const track = document.createElement('div');
    track.classList.add('ticker-track');
    if (pauseOnHover) track.classList.add('ticker-pause-on-hover');
    track.setAttribute('data-ticker-track', '');

    const newContent = document.createElement('div');
    newContent.classList.add('ticker-content');
    newContent.setAttribute('data-ticker-content', '');

    while (content.firstChild) {
      newContent.appendChild(content.firstChild);
    }

    track.appendChild(newContent);
    wrapper.appendChild(track);

    const tickerInstance = createTicker({ duration, direction, pauseOnHover, class: className });
    tickerInstance.mount();

    setIsReady(true);

    return () => {
      tickerInstance.unmount();
    };
  }, [duration, direction, pauseOnHover, className]);

  const combinedClassName = `ticker-wrapper ${className}`.trim();

  return (
    <Component
      ref={containerRef}
      className={combinedClassName}
      data-ticker=""
      data-duration={duration}
      data-direction={direction}
      data-pause-on-hover={pauseOnHover ? 'true' : 'false'}
      data-ready={isReady ? 'true' : 'false'}
      data-active="true"
      style={{ '--ticker-duration': `${duration}s` } as React.CSSProperties}
      {...props}
    >
      <div
        className={`ticker-track ${pauseOnHover ? 'ticker-pause-on-hover' : ''}`}
        data-ticker-track=""
      >
        <div className="ticker-content" data-ticker-content="">
          {children}
        </div>
      </div>
    </Component>
  );
}

export function Content({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  return <div className={`ticker-content ${className}`}>{children}</div>;
}

export const Ticker = {
  Root,
  Content,
};

export default Ticker;

// src/vue/Ticker.vue
<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, computed } from 'vue';
import type { TickerOptions } from '../core/types';
import { createTicker, mount, unmount } from '../vanilla/render';
import '../style.css';

interface Props extends TickerOptions {
  as?: 'div' | 'section' | 'article' | 'nav' | 'footer' | 'header';
}

const props = withDefaults(defineProps<Props>(), {
  duration: 20,
  direction: 'left',
  pauseOnHover: false,
  class: '',
  as: 'div',
});

const emit = defineEmits<{
  ready: [];
}>();

const containerRef = ref<HTMLElement | null>(null);
const isReady = ref(false);
let tickerInstance: ReturnType<typeof createTicker> | null = null;

const combinedClass = computed(() => {
  return `ticker-wrapper ${props.class}`.trim();
});

onMounted(() => {
  mount();

  const container = containerRef.value;
  if (!container) return;

  setTimeout(() => {
    isReady.value = true;
    emit('ready');
  }, 0);

  tickerInstance = createTicker({
    duration: props.duration,
    direction: props.direction,
    pauseOnHover: props.pauseOnHover,
    class: props.class,
  });
  tickerInstance.mount();
});

onBeforeUnmount(() => {
  if (tickerInstance) {
    tickerInstance.unmount();
  }
});
</script>

<template>
  <component
    :is="props.as"
    ref="containerRef"
    :class="combinedClass"
    data-ticker=""
    :data-duration="props.duration"
    :data-direction="props.direction"
    :data-pause-on-hover="props.pauseOnHover ? 'true' : 'false'"
    :data-ready="isReady ? 'true' : 'false'"
    data-active="true"
    :style="{ '--ticker-duration': `${props.duration}s` }"
  >
    <div
      :class="['ticker-track', props.pauseOnHover ? 'ticker-pause-on-hover' : '']"
      data-ticker-track=""
    >
      <div class="ticker-content" data-ticker-content="">
        <slot />
      </div>
    </div>
  </component>
</template>
